/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import domain.Apartment;
import domain.Controller;
import domain.Customer;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Container;
import java.awt.Frame;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 * @author Robert
 */
public class CasablancaGUI extends javax.swing.JFrame {

    CardLayout cl;
    Controller controller;
    DefaultListModel listModel;

    /**
     * Creates new form CasablancaGUI
     */
    public CasablancaGUI() {
        initComponents();
        this.controller = new Controller();
        cl = (CardLayout) (mainPage.getLayout());
        cl.addLayoutComponent(frontPagePanel, "FrontPage");
        cl.addLayoutComponent(newBookingPanel, "NewBooking");
        cl.addLayoutComponent(editBookingPanel, "EditBooking");
        cl.show(mainPage, "FrontPage");
        this.setExtendedState(Frame.MAXIMIZED_BOTH);
        this.dispose();
        this.setUndecorated(true);
        this.frontPageLogoutButton.setVisible(false);
        this.newBookingFormPreviousButton.setVisible(false);

        listModel = new DefaultListModel();
        this.newBookingAvailList.setModel(listModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPage = new javax.swing.JPanel();
        frontPagePanel = new javax.swing.JPanel();
        frontPageMenuPanel = new javax.swing.JPanel();
        frontPageLogoutButton = new javax.swing.JButton();
        frontPageExitButton = new javax.swing.JButton();
        frontPageNavPanel = new javax.swing.JPanel();
        frontPageNewBooking = new javax.swing.JButton();
        frontPageEditBooking = new javax.swing.JButton();
        newBookingPanel = new javax.swing.JPanel();
        newBookingTitlePanel = new javax.swing.JPanel();
        newBookingTitleTitle = new javax.swing.JLabel();
        newBookingFindPanel = new javax.swing.JPanel();
        newBookingFindTitlePanel = new javax.swing.JPanel();
        newBookingFindTitleTitle = new javax.swing.JLabel();
        newBookingFindSearchPanel = new javax.swing.JPanel();
        newBookingFindSearchFromLabel = new javax.swing.JLabel();
        newBookingFindSearchNONLabel = new javax.swing.JLabel();
        newBookingFindSearchFromTextField = new javax.swing.JTextField();
        newBookingFindSearchNONTextField = new javax.swing.JTextField();
        newBookingFindSearchTypeComboBox = new javax.swing.JComboBox();
        newBookingFindSearchTypeLabel = new javax.swing.JLabel();
        newBookingFindButtonPanel = new javax.swing.JPanel();
        newBookingFindButtonBackButton = new javax.swing.JButton();
        newBookingFindButtonFindButton = new javax.swing.JButton();
        newBookingAvailablePanel = new javax.swing.JPanel();
        newBookingAvailTitlePanel = new javax.swing.JPanel();
        newBookingAvailTitleTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        newBookingAvailList = new javax.swing.JList();
        newBookingFormPanel = new javax.swing.JPanel();
        newBookingFormTitlePanel = new javax.swing.JPanel();
        newBookingFormTitleTitle = new javax.swing.JLabel();
        newBookingFormFirstLabel = new javax.swing.JLabel();
        newBookingFormFirstTextField = new javax.swing.JTextField();
        newBookingFormNameLabel = new javax.swing.JLabel();
        newBookingFormNameTextField = new javax.swing.JTextField();
        newBookingFormAGELabel = new javax.swing.JLabel();
        newBookingFormNOGLabel = new javax.swing.JLabel();
        newBookingFormNOGTextField = new javax.swing.JTextField();
        newBookingFormCityLabel = new javax.swing.JLabel();
        newBookingFormPhoneTextField = new javax.swing.JTextField();
        newBookingFormNatLabel = new javax.swing.JLabel();
        newBookingFormNatTextField = new javax.swing.JTextField();
        newBookingFormStreetLabel = new javax.swing.JLabel();
        newBookingFormPhoneLabel = new javax.swing.JLabel();
        newBookingFormCityTextField = new javax.swing.JTextField();
        newBookingFormStreetTextField = new javax.swing.JTextField();
        newBookingFormButtonPanel = new javax.swing.JPanel();
        newBookingFormCreateButton = new javax.swing.JButton();
        newBookingFormPreviousButton = new javax.swing.JButton();
        newBookingFormButtonSaveButton = new javax.swing.JButton();
        newBookingFormGreyPanel = new javax.swing.JPanel();
        newBookingFormADateLabel = new javax.swing.JLabel();
        newBookingFormNONLabel = new javax.swing.JLabel();
        newBookingFormRoomLabel = new javax.swing.JLabel();
        newBookingFormADateTextField = new javax.swing.JTextField();
        newBookingFormNONTextField = new javax.swing.JTextField();
        newBookingFormRoomTextField = new javax.swing.JTextField();
        newBookingFormAgenLabel = new javax.swing.JLabel();
        newBookingFormAgenTextField = new javax.swing.JTextField();
        newBookingFormEmailLabel = new javax.swing.JLabel();
        newBookingFormEmailTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        newBookingFormZipTextField = new javax.swing.JTextField();
        newBookingFormAGETextField = new javax.swing.JTextField();
        editBookingPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setResizable(false);

        mainPage.setMaximumSize(new java.awt.Dimension(1366, 768));
        mainPage.setMinimumSize(new java.awt.Dimension(1366, 768));
        mainPage.setPreferredSize(new java.awt.Dimension(1366, 768));
        mainPage.setLayout(new java.awt.CardLayout());

        frontPagePanel.setMaximumSize(new java.awt.Dimension(1366, 768));
        frontPagePanel.setMinimumSize(new java.awt.Dimension(1366, 768));
        frontPagePanel.setPreferredSize(new java.awt.Dimension(1366, 768));

        frontPageMenuPanel.setMaximumSize(new java.awt.Dimension(200, 768));
        frontPageMenuPanel.setMinimumSize(new java.awt.Dimension(200, 768));
        frontPageMenuPanel.setPreferredSize(new java.awt.Dimension(200, 768));

        frontPageLogoutButton.setText("Logout");
        frontPageLogoutButton.setMaximumSize(new java.awt.Dimension(76, 25));
        frontPageLogoutButton.setMinimumSize(new java.awt.Dimension(76, 25));
        frontPageLogoutButton.setPreferredSize(new java.awt.Dimension(76, 25));

        frontPageExitButton.setText("Exit");
        frontPageExitButton.setMaximumSize(new java.awt.Dimension(76, 25));
        frontPageExitButton.setMinimumSize(new java.awt.Dimension(76, 25));
        frontPageExitButton.setPreferredSize(new java.awt.Dimension(76, 25));
        frontPageExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frontPageExitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frontPageMenuPanelLayout = new javax.swing.GroupLayout(frontPageMenuPanel);
        frontPageMenuPanel.setLayout(frontPageMenuPanelLayout);
        frontPageMenuPanelLayout.setHorizontalGroup(
            frontPageMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frontPageMenuPanelLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(frontPageMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(frontPageLogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(frontPageExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        frontPageMenuPanelLayout.setVerticalGroup(
            frontPageMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frontPageMenuPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(frontPageLogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(frontPageExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        frontPageNavPanel.setMaximumSize(new java.awt.Dimension(1166, 768));
        frontPageNavPanel.setMinimumSize(new java.awt.Dimension(1166, 768));
        frontPageNavPanel.setPreferredSize(new java.awt.Dimension(1166, 768));

        frontPageNewBooking.setText("New Booking");
        frontPageNewBooking.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        frontPageNewBooking.setMaximumSize(new java.awt.Dimension(150, 50));
        frontPageNewBooking.setMinimumSize(new java.awt.Dimension(150, 50));
        frontPageNewBooking.setPreferredSize(new java.awt.Dimension(150, 50));
        frontPageNewBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frontPageNewBookingActionPerformed(evt);
            }
        });

        frontPageEditBooking.setText("Edit Booking");
        frontPageEditBooking.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        frontPageEditBooking.setMaximumSize(new java.awt.Dimension(150, 50));
        frontPageEditBooking.setMinimumSize(new java.awt.Dimension(150, 50));
        frontPageEditBooking.setPreferredSize(new java.awt.Dimension(150, 50));
        frontPageEditBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frontPageEditBookingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frontPageNavPanelLayout = new javax.swing.GroupLayout(frontPageNavPanel);
        frontPageNavPanel.setLayout(frontPageNavPanelLayout);
        frontPageNavPanelLayout.setHorizontalGroup(
            frontPageNavPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frontPageNavPanelLayout.createSequentialGroup()
                .addGap(408, 408, 408)
                .addGroup(frontPageNavPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(frontPageNewBooking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(frontPageEditBooking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(608, Short.MAX_VALUE))
        );
        frontPageNavPanelLayout.setVerticalGroup(
            frontPageNavPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frontPageNavPanelLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(frontPageNewBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(frontPageEditBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout frontPagePanelLayout = new javax.swing.GroupLayout(frontPagePanel);
        frontPagePanel.setLayout(frontPagePanelLayout);
        frontPagePanelLayout.setHorizontalGroup(
            frontPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frontPagePanelLayout.createSequentialGroup()
                .addComponent(frontPageMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(frontPageNavPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        frontPagePanelLayout.setVerticalGroup(
            frontPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(frontPageMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(frontPageNavPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mainPage.add(frontPagePanel, "card2");

        newBookingPanel.setMaximumSize(new java.awt.Dimension(1366, 768));
        newBookingPanel.setMinimumSize(new java.awt.Dimension(1366, 768));
        newBookingPanel.setPreferredSize(new java.awt.Dimension(1366, 768));

        newBookingTitlePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        newBookingTitlePanel.setMaximumSize(new java.awt.Dimension(1366, 40));
        newBookingTitlePanel.setMinimumSize(new java.awt.Dimension(1366, 40));
        newBookingTitlePanel.setPreferredSize(new java.awt.Dimension(1366, 40));

        newBookingTitleTitle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        newBookingTitleTitle.setText("New Booking");

        javax.swing.GroupLayout newBookingTitlePanelLayout = new javax.swing.GroupLayout(newBookingTitlePanel);
        newBookingTitlePanel.setLayout(newBookingTitlePanelLayout);
        newBookingTitlePanelLayout.setHorizontalGroup(
            newBookingTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newBookingTitlePanelLayout.createSequentialGroup()
                .addGap(625, 625, 625)
                .addComponent(newBookingTitleTitle)
                .addContainerGap(623, Short.MAX_VALUE))
        );
        newBookingTitlePanelLayout.setVerticalGroup(
            newBookingTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newBookingTitlePanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(newBookingTitleTitle)
                .addContainerGap(6, Short.MAX_VALUE))
        );

        newBookingFindPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        newBookingFindPanel.setMaximumSize(new java.awt.Dimension(455, 728));
        newBookingFindPanel.setMinimumSize(new java.awt.Dimension(455, 728));
        newBookingFindPanel.setPreferredSize(new java.awt.Dimension(455, 728));

        newBookingFindTitlePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        newBookingFindTitlePanel.setMinimumSize(new java.awt.Dimension(453, 40));
        newBookingFindTitlePanel.setPreferredSize(new java.awt.Dimension(453, 40));

        newBookingFindTitleTitle.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        newBookingFindTitleTitle.setText("Find Apartment");

        javax.swing.GroupLayout newBookingFindTitlePanelLayout = new javax.swing.GroupLayout(newBookingFindTitlePanel);
        newBookingFindTitlePanel.setLayout(newBookingFindTitlePanelLayout);
        newBookingFindTitlePanelLayout.setHorizontalGroup(
            newBookingFindTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newBookingFindTitlePanelLayout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(newBookingFindTitleTitle)
                .addContainerGap(195, Short.MAX_VALUE))
        );
        newBookingFindTitlePanelLayout.setVerticalGroup(
            newBookingFindTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newBookingFindTitlePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(newBookingFindTitleTitle)
                .addContainerGap())
        );

        newBookingFindSearchPanel.setMaximumSize(new java.awt.Dimension(453, 630));
        newBookingFindSearchPanel.setMinimumSize(new java.awt.Dimension(453, 630));
        newBookingFindSearchPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newBookingFindSearchPanelMouseClicked(evt);
            }
        });

        newBookingFindSearchFromLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        newBookingFindSearchFromLabel.setText("From:");

        newBookingFindSearchNONLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        newBookingFindSearchNONLabel.setText("Number of nights:");

        newBookingFindSearchFromTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        newBookingFindSearchFromTextField.setText("DD-MM-YY");
        newBookingFindSearchFromTextField.setMaximumSize(new java.awt.Dimension(58, 19));
        newBookingFindSearchFromTextField.setMinimumSize(new java.awt.Dimension(58, 19));
        newBookingFindSearchFromTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newBookingFindSearchFromTextFieldMouseClicked(evt);
            }
        });
        newBookingFindSearchFromTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBookingFindSearchFromTextFieldActionPerformed(evt);
            }
        });

        newBookingFindSearchNONTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        newBookingFindSearchNONTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newBookingFindSearchNONTextFieldMouseClicked(evt);
            }
        });

        newBookingFindSearchTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Single", "Double", "Family" }));
        newBookingFindSearchTypeComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newBookingFindSearchTypeComboBoxMouseClicked(evt);
            }
        });

        newBookingFindSearchTypeLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        newBookingFindSearchTypeLabel.setText("Type:");

        javax.swing.GroupLayout newBookingFindSearchPanelLayout = new javax.swing.GroupLayout(newBookingFindSearchPanel);
        newBookingFindSearchPanel.setLayout(newBookingFindSearchPanelLayout);
        newBookingFindSearchPanelLayout.setHorizontalGroup(
            newBookingFindSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newBookingFindSearchPanelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(newBookingFindSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, newBookingFindSearchPanelLayout.createSequentialGroup()
                        .addComponent(newBookingFindSearchFromLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(newBookingFindSearchFromTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, newBookingFindSearchPanelLayout.createSequentialGroup()
                        .addComponent(newBookingFindSearchTypeLabel)
                        .addGap(26, 26, 26)
                        .addComponent(newBookingFindSearchTypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, newBookingFindSearchPanelLayout.createSequentialGroup()
                        .addComponent(newBookingFindSearchNONLabel)
                        .addGap(30, 30, 30)
                        .addComponent(newBookingFindSearchNONTextField)))
                .addGap(100, 100, 100))
        );
        newBookingFindSearchPanelLayout.setVerticalGroup(
            newBookingFindSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newBookingFindSearchPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(newBookingFindSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newBookingFindSearchFromLabel)
                    .addComponent(newBookingFindSearchFromTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newBookingFindSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newBookingFindSearchNONTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newBookingFindSearchNONLabel))
                .addGap(18, 18, 18)
                .addGroup(newBookingFindSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newBookingFindSearchTypeLabel)
                    .addComponent(newBookingFindSearchTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        newBookingFindButtonPanel.setMaximumSize(new java.awt.Dimension(453, 50));
        newBookingFindButtonPanel.setMinimumSize(new java.awt.Dimension(453, 50));
        newBookingFindButtonPanel.setPreferredSize(new java.awt.Dimension(453, 50));

        newBookingFindButtonBackButton.setText("Back");
        newBookingFindButtonBackButton.setMaximumSize(new java.awt.Dimension(100, 30));
        newBookingFindButtonBackButton.setMinimumSize(new java.awt.Dimension(100, 30));
        newBookingFindButtonBackButton.setPreferredSize(new java.awt.Dimension(100, 30));
        newBookingFindButtonBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBookingFindButtonBackButtonActionPerformed(evt);
            }
        });

        newBookingFindButtonFindButton.setText("Find");
        newBookingFindButtonFindButton.setMaximumSize(new java.awt.Dimension(100, 30));
        newBookingFindButtonFindButton.setMinimumSize(new java.awt.Dimension(100, 30));
        newBookingFindButtonFindButton.setPreferredSize(new java.awt.Dimension(100, 30));
        newBookingFindButtonFindButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBookingFindButtonFindButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newBookingFindButtonPanelLayout = new javax.swing.GroupLayout(newBookingFindButtonPanel);
        newBookingFindButtonPanel.setLayout(newBookingFindButtonPanelLayout);
        newBookingFindButtonPanelLayout.setHorizontalGroup(
            newBookingFindButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newBookingFindButtonPanelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(newBookingFindButtonBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(newBookingFindButtonFindButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        newBookingFindButtonPanelLayout.setVerticalGroup(
            newBookingFindButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newBookingFindButtonPanelLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(newBookingFindButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newBookingFindButtonBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newBookingFindButtonFindButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout newBookingFindPanelLayout = new javax.swing.GroupLayout(newBookingFindPanel);
        newBookingFindPanel.setLayout(newBookingFindPanelLayout);
        newBookingFindPanelLayout.setHorizontalGroup(
            newBookingFindPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newBookingFindPanelLayout.createSequentialGroup()
                .addComponent(newBookingFindTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(newBookingFindPanelLayout.createSequentialGroup()
                .addGroup(newBookingFindPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(newBookingFindButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newBookingFindSearchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        newBookingFindPanelLayout.setVerticalGroup(
            newBookingFindPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newBookingFindPanelLayout.createSequentialGroup()
                .addComponent(newBookingFindTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newBookingFindSearchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newBookingFindButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
        );

        newBookingAvailablePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        newBookingAvailablePanel.setMaximumSize(new java.awt.Dimension(455, 728));
        newBookingAvailablePanel.setMinimumSize(new java.awt.Dimension(455, 728));
        newBookingAvailablePanel.setPreferredSize(new java.awt.Dimension(455, 728));

        newBookingAvailTitlePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        newBookingAvailTitlePanel.setMaximumSize(new java.awt.Dimension(453, 40));
        newBookingAvailTitlePanel.setMinimumSize(new java.awt.Dimension(453, 40));
        newBookingAvailTitlePanel.setPreferredSize(new java.awt.Dimension(453, 40));

        newBookingAvailTitleTitle.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        newBookingAvailTitleTitle.setText("Available Apartments");

        javax.swing.GroupLayout newBookingAvailTitlePanelLayout = new javax.swing.GroupLayout(newBookingAvailTitlePanel);
        newBookingAvailTitlePanel.setLayout(newBookingAvailTitlePanelLayout);
        newBookingAvailTitlePanelLayout.setHorizontalGroup(
            newBookingAvailTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newBookingAvailTitlePanelLayout.createSequentialGroup()
                .addContainerGap(165, Short.MAX_VALUE)
                .addComponent(newBookingAvailTitleTitle)
                .addGap(165, 165, 165))
        );
        newBookingAvailTitlePanelLayout.setVerticalGroup(
            newBookingAvailTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newBookingAvailTitlePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(newBookingAvailTitleTitle)
                .addContainerGap())
        );

        newBookingAvailList.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        newBookingAvailList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newBookingAvailListMouseClicked(evt);
            }
        });
        newBookingAvailList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                newBookingAvailListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(newBookingAvailList);

        javax.swing.GroupLayout newBookingAvailablePanelLayout = new javax.swing.GroupLayout(newBookingAvailablePanel);
        newBookingAvailablePanel.setLayout(newBookingAvailablePanelLayout);
        newBookingAvailablePanelLayout.setHorizontalGroup(
            newBookingAvailablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newBookingAvailTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        newBookingAvailablePanelLayout.setVerticalGroup(
            newBookingAvailablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newBookingAvailablePanelLayout.createSequentialGroup()
                .addComponent(newBookingAvailTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1))
        );

        newBookingFormPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        newBookingFormPanel.setMaximumSize(new java.awt.Dimension(456, 728));
        newBookingFormPanel.setMinimumSize(new java.awt.Dimension(456, 728));
        newBookingFormPanel.setPreferredSize(new java.awt.Dimension(456, 728));

        newBookingFormTitlePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        newBookingFormTitlePanel.setMaximumSize(new java.awt.Dimension(453, 40));
        newBookingFormTitlePanel.setMinimumSize(new java.awt.Dimension(453, 40));
        newBookingFormTitlePanel.setPreferredSize(new java.awt.Dimension(453, 40));

        newBookingFormTitleTitle.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        newBookingFormTitleTitle.setText("Booking Form");

        javax.swing.GroupLayout newBookingFormTitlePanelLayout = new javax.swing.GroupLayout(newBookingFormTitlePanel);
        newBookingFormTitlePanel.setLayout(newBookingFormTitlePanelLayout);
        newBookingFormTitlePanelLayout.setHorizontalGroup(
            newBookingFormTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newBookingFormTitlePanelLayout.createSequentialGroup()
                .addContainerGap(187, Short.MAX_VALUE)
                .addComponent(newBookingFormTitleTitle)
                .addGap(186, 186, 186))
        );
        newBookingFormTitlePanelLayout.setVerticalGroup(
            newBookingFormTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newBookingFormTitlePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(newBookingFormTitleTitle)
                .addContainerGap())
        );

        newBookingFormFirstLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        newBookingFormFirstLabel.setText("First Name:");

        newBookingFormFirstTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        newBookingFormFirstTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBookingFormFirstTextFieldActionPerformed(evt);
            }
        });

        newBookingFormNameLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        newBookingFormNameLabel.setText("Family Name:");

        newBookingFormNameTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        newBookingFormAGELabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        newBookingFormAGELabel.setText("Age:");

        newBookingFormNOGLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        newBookingFormNOGLabel.setText("Number of Guests:");

        newBookingFormNOGTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        newBookingFormCityLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        newBookingFormCityLabel.setText("City:");

        newBookingFormPhoneTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        newBookingFormNatLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        newBookingFormNatLabel.setText("Nationality: ");

        newBookingFormNatTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        newBookingFormStreetLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        newBookingFormStreetLabel.setText("Street:");

        newBookingFormPhoneLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        newBookingFormPhoneLabel.setText("Phone:");

        newBookingFormCityTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        newBookingFormStreetTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        newBookingFormCreateButton.setText("Create Booking");
        newBookingFormCreateButton.setMaximumSize(new java.awt.Dimension(107, 30));
        newBookingFormCreateButton.setMinimumSize(new java.awt.Dimension(107, 30));
        newBookingFormCreateButton.setPreferredSize(new java.awt.Dimension(107, 30));
        newBookingFormCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBookingFormCreateButtonActionPerformed(evt);
            }
        });

        newBookingFormPreviousButton.setText("Previous Customer");
        newBookingFormPreviousButton.setMaximumSize(new java.awt.Dimension(125, 30));
        newBookingFormPreviousButton.setMinimumSize(new java.awt.Dimension(125, 30));
        newBookingFormPreviousButton.setPreferredSize(new java.awt.Dimension(125, 30));
        newBookingFormPreviousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBookingFormPreviousButtonActionPerformed(evt);
            }
        });

        newBookingFormButtonSaveButton.setText("Save All");
        newBookingFormButtonSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBookingFormButtonSaveButtonActionPerformed(evt);
            }
        });

        newBookingFormADateLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        newBookingFormADateLabel.setText("Arrival Date:");

        newBookingFormNONLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        newBookingFormNONLabel.setText("Number of Nights:");

        newBookingFormRoomLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        newBookingFormRoomLabel.setText("Room:");

        newBookingFormADateTextField.setEditable(false);
        newBookingFormADateTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        newBookingFormADateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBookingFormADateTextFieldActionPerformed(evt);
            }
        });

        newBookingFormNONTextField.setEditable(false);
        newBookingFormNONTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        newBookingFormRoomTextField.setEditable(false);
        newBookingFormRoomTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout newBookingFormGreyPanelLayout = new javax.swing.GroupLayout(newBookingFormGreyPanel);
        newBookingFormGreyPanel.setLayout(newBookingFormGreyPanelLayout);
        newBookingFormGreyPanelLayout.setHorizontalGroup(
            newBookingFormGreyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newBookingFormGreyPanelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(newBookingFormGreyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newBookingFormRoomLabel)
                    .addComponent(newBookingFormNONLabel)
                    .addComponent(newBookingFormADateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newBookingFormGreyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newBookingFormRoomTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addComponent(newBookingFormADateTextField)
                    .addComponent(newBookingFormNONTextField, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(94, 94, 94))
        );
        newBookingFormGreyPanelLayout.setVerticalGroup(
            newBookingFormGreyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newBookingFormGreyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newBookingFormGreyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newBookingFormADateLabel)
                    .addComponent(newBookingFormADateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newBookingFormGreyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newBookingFormNONLabel)
                    .addComponent(newBookingFormNONTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newBookingFormGreyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newBookingFormRoomLabel)
                    .addComponent(newBookingFormRoomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout newBookingFormButtonPanelLayout = new javax.swing.GroupLayout(newBookingFormButtonPanel);
        newBookingFormButtonPanel.setLayout(newBookingFormButtonPanelLayout);
        newBookingFormButtonPanelLayout.setHorizontalGroup(
            newBookingFormButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newBookingFormButtonPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(newBookingFormCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newBookingFormButtonSaveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newBookingFormPreviousButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addComponent(newBookingFormGreyPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        newBookingFormButtonPanelLayout.setVerticalGroup(
            newBookingFormButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newBookingFormButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newBookingFormGreyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addGroup(newBookingFormButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newBookingFormPreviousButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newBookingFormCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newBookingFormButtonSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        newBookingFormAgenLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        newBookingFormAgenLabel.setText("Agency:");

        newBookingFormAgenTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        newBookingFormAgenTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBookingFormAgenTextFieldActionPerformed(evt);
            }
        });

        newBookingFormEmailLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        newBookingFormEmailLabel.setText("Email:");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("ZipCode:");

        javax.swing.GroupLayout newBookingFormPanelLayout = new javax.swing.GroupLayout(newBookingFormPanel);
        newBookingFormPanel.setLayout(newBookingFormPanelLayout);
        newBookingFormPanelLayout.setHorizontalGroup(
            newBookingFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newBookingFormPanelLayout.createSequentialGroup()
                .addComponent(newBookingFormTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
            .addComponent(newBookingFormButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(newBookingFormPanelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(newBookingFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(newBookingFormPanelLayout.createSequentialGroup()
                        .addComponent(newBookingFormNOGLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(newBookingFormNOGTextField))
                    .addGroup(newBookingFormPanelLayout.createSequentialGroup()
                        .addComponent(newBookingFormPhoneLabel)
                        .addGap(27, 27, 27)
                        .addComponent(newBookingFormPhoneTextField))
                    .addGroup(newBookingFormPanelLayout.createSequentialGroup()
                        .addComponent(newBookingFormEmailLabel)
                        .addGap(29, 29, 29)
                        .addComponent(newBookingFormEmailTextField))
                    .addGroup(newBookingFormPanelLayout.createSequentialGroup()
                        .addComponent(newBookingFormCityLabel)
                        .addGap(29, 29, 29)
                        .addComponent(newBookingFormCityTextField))
                    .addGroup(newBookingFormPanelLayout.createSequentialGroup()
                        .addComponent(newBookingFormStreetLabel)
                        .addGap(29, 29, 29)
                        .addComponent(newBookingFormStreetTextField))
                    .addGroup(newBookingFormPanelLayout.createSequentialGroup()
                        .addComponent(newBookingFormAgenLabel)
                        .addGap(62, 62, 62)
                        .addComponent(newBookingFormAgenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newBookingFormPanelLayout.createSequentialGroup()
                        .addComponent(newBookingFormFirstLabel)
                        .addGap(30, 30, 30)
                        .addComponent(newBookingFormFirstTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newBookingFormPanelLayout.createSequentialGroup()
                        .addGroup(newBookingFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newBookingFormNatLabel)
                            .addComponent(jLabel1))
                        .addGap(36, 36, 36)
                        .addGroup(newBookingFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newBookingFormZipTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newBookingFormNatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(newBookingFormPanelLayout.createSequentialGroup()
                        .addGroup(newBookingFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newBookingFormNameLabel)
                            .addComponent(newBookingFormAGELabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(newBookingFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newBookingFormAGETextField)
                            .addComponent(newBookingFormNameTextField))))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        newBookingFormPanelLayout.setVerticalGroup(
            newBookingFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newBookingFormPanelLayout.createSequentialGroup()
                .addComponent(newBookingFormTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(newBookingFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newBookingFormFirstLabel)
                    .addComponent(newBookingFormFirstTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(newBookingFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newBookingFormNameLabel)
                    .addComponent(newBookingFormNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(newBookingFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newBookingFormAGELabel)
                    .addComponent(newBookingFormAGETextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(newBookingFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newBookingFormNOGLabel)
                    .addComponent(newBookingFormNOGTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(newBookingFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newBookingFormPhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newBookingFormPhoneLabel))
                .addGap(10, 10, 10)
                .addGroup(newBookingFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newBookingFormEmailLabel)
                    .addComponent(newBookingFormEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(newBookingFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newBookingFormCityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newBookingFormCityLabel))
                .addGap(9, 9, 9)
                .addGroup(newBookingFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newBookingFormStreetTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newBookingFormStreetLabel))
                .addGap(10, 10, 10)
                .addGroup(newBookingFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(newBookingFormZipTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(newBookingFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newBookingFormNatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newBookingFormNatLabel))
                .addGap(10, 10, 10)
                .addGroup(newBookingFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newBookingFormAgenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newBookingFormAgenLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newBookingFormButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout newBookingPanelLayout = new javax.swing.GroupLayout(newBookingPanel);
        newBookingPanel.setLayout(newBookingPanelLayout);
        newBookingPanelLayout.setHorizontalGroup(
            newBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newBookingPanelLayout.createSequentialGroup()
                .addComponent(newBookingFindPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(newBookingAvailablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(newBookingFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(newBookingTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        newBookingPanelLayout.setVerticalGroup(
            newBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newBookingPanelLayout.createSequentialGroup()
                .addComponent(newBookingTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(newBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newBookingFormPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(newBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(newBookingAvailablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(newBookingFindPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        mainPage.add(newBookingPanel, "card3");

        editBookingPanel.setMaximumSize(new java.awt.Dimension(1366, 768));
        editBookingPanel.setMinimumSize(new java.awt.Dimension(1366, 768));
        editBookingPanel.setPreferredSize(new java.awt.Dimension(1366, 768));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setMaximumSize(new java.awt.Dimension(1366, 40));
        jPanel1.setMinimumSize(new java.awt.Dimension(1366, 40));
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 40));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Edit Booking");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(626, 626, 626)
                .addComponent(jLabel2)
                .addContainerGap(627, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel2)
                .addContainerGap(6, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setMaximumSize(new java.awt.Dimension(453, 728));
        jPanel2.setMinimumSize(new java.awt.Dimension(453, 728));
        jPanel2.setPreferredSize(new java.awt.Dimension(453, 728));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setMaximumSize(new java.awt.Dimension(451, 40));
        jPanel5.setMinimumSize(new java.awt.Dimension(451, 40));
        jPanel5.setPreferredSize(new java.awt.Dimension(451, 40));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Find Booking");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jButton1.setText("Back");
        jButton1.setMaximumSize(new java.awt.Dimension(100, 30));
        jButton1.setMinimumSize(new java.awt.Dimension(100, 30));
        jButton1.setPreferredSize(new java.awt.Dimension(100, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Find");
        jButton2.setMaximumSize(new java.awt.Dimension(100, 30));
        jButton2.setMinimumSize(new java.awt.Dimension(100, 30));
        jButton2.setPreferredSize(new java.awt.Dimension(100, 30));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Booking nr:");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Name:");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Date:");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("Room nr:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(jTextField2)
                            .addComponent(jTextField4))))
                .addGap(100, 100, 100))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 423, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setMaximumSize(new java.awt.Dimension(453, 728));
        jPanel3.setMinimumSize(new java.awt.Dimension(453, 728));
        jPanel3.setPreferredSize(new java.awt.Dimension(453, 728));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setMaximumSize(new java.awt.Dimension(451, 40));
        jPanel6.setMinimumSize(new java.awt.Dimension(451, 40));
        jPanel6.setPreferredSize(new java.awt.Dimension(451, 40));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Matching Bookings");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jLabel4)
                .addContainerGap(157, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jList1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setMaximumSize(new java.awt.Dimension(456, 728));
        jPanel4.setMinimumSize(new java.awt.Dimension(456, 728));
        jPanel4.setPreferredSize(new java.awt.Dimension(456, 728));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setMaximumSize(new java.awt.Dimension(458, 40));
        jPanel7.setMinimumSize(new java.awt.Dimension(458, 40));
        jPanel7.setPreferredSize(new java.awt.Dimension(458, 40));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Booking Info");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(jLabel5)
                .addContainerGap(183, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel5)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jButton3.setText("Edit");
        jButton3.setMaximumSize(new java.awt.Dimension(100, 30));
        jButton3.setMinimumSize(new java.awt.Dimension(100, 30));
        jButton3.setPreferredSize(new java.awt.Dimension(100, 30));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Delete");
        jButton4.setMaximumSize(new java.awt.Dimension(100, 30));
        jButton4.setMinimumSize(new java.awt.Dimension(100, 30));
        jButton4.setPreferredSize(new java.awt.Dimension(100, 30));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 301, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout editBookingPanelLayout = new javax.swing.GroupLayout(editBookingPanel);
        editBookingPanel.setLayout(editBookingPanelLayout);
        editBookingPanelLayout.setHorizontalGroup(
            editBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editBookingPanelLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        editBookingPanelLayout.setVerticalGroup(
            editBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editBookingPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(editBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editBookingPanelLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(editBookingPanelLayout.createSequentialGroup()
                        .addGroup(editBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        mainPage.add(editBookingPanel, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mainPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void frontPageEditBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frontPageEditBookingActionPerformed
        cl.show(mainPage, "EditBooking");
    }//GEN-LAST:event_frontPageEditBookingActionPerformed

    private void frontPageNewBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frontPageNewBookingActionPerformed
        cl.show(mainPage, "NewBooking");
        this.enableComponents(this.newBookingAvailablePanel, false);
        this.enableComponents(this.newBookingFormPanel, false);
    }//GEN-LAST:event_frontPageNewBookingActionPerformed

    private void frontPageExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frontPageExitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_frontPageExitButtonActionPerformed

    private void newBookingFindButtonBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBookingFindButtonBackButtonActionPerformed
        cl.show(mainPage, "FrontPage");
    }//GEN-LAST:event_newBookingFindButtonBackButtonActionPerformed

    /**
     * @param container
     * @param enable set true to enable components in container
     * @author Robert Elving
     */
    public void enableComponents(Container container, boolean enable) {
        Component[] components = container.getComponents();
        for (Component component : components) {
            component.setEnabled(enable);
            if (component instanceof Container) {
                enableComponents((Container) component, enable);
            }
        }
    }

    private void newBookingFindSearchFromTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBookingFindSearchFromTextFieldActionPerformed
        this.enableComponents(this.newBookingAvailablePanel, false);
        this.enableComponents(this.newBookingFormPanel, false);
    }//GEN-LAST:event_newBookingFindSearchFromTextFieldActionPerformed

    private void newBookingFindButtonFindButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBookingFindButtonFindButtonActionPerformed

        Apartment a = controller.findAvailableApartment(this.newBookingFindSearchFromTextField.getText(), Integer.parseInt(this.newBookingFindSearchNONTextField.getText()), this.newBookingFindSearchTypeComboBox.getSelectedItem().toString());
        if (a == null) {

            this.enableComponents(this, false);
            JOptionPane.showMessageDialog(this, "No available appartment", "", WIDTH);
            this.enableComponents(this, true);
            this.enableComponents(this.newBookingFormPanel, false);
            this.enableComponents(this.newBookingAvailablePanel, false);

        } else {
            this.listModel.addElement(a);
            this.enableComponents(this.newBookingAvailablePanel, true);
        }
    }//GEN-LAST:event_newBookingFindButtonFindButtonActionPerformed

    private void newBookingFindSearchPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newBookingFindSearchPanelMouseClicked
    }//GEN-LAST:event_newBookingFindSearchPanelMouseClicked

    private void newBookingFindSearchFromTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newBookingFindSearchFromTextFieldMouseClicked
        this.newBookingFindSearchFromTextField.setText("");
        this.enableComponents(this.newBookingAvailablePanel, false);
        this.enableComponents(this.newBookingFormPanel, false);
    }//GEN-LAST:event_newBookingFindSearchFromTextFieldMouseClicked

    private void newBookingFindSearchNONTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newBookingFindSearchNONTextFieldMouseClicked
        this.enableComponents(this.newBookingAvailablePanel, false);
        this.enableComponents(this.newBookingFormPanel, false);
    }//GEN-LAST:event_newBookingFindSearchNONTextFieldMouseClicked

    private void newBookingFindSearchTypeComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newBookingFindSearchTypeComboBoxMouseClicked
        this.enableComponents(this.newBookingAvailablePanel, false);
        this.enableComponents(this.newBookingFormPanel, false);
    }//GEN-LAST:event_newBookingFindSearchTypeComboBoxMouseClicked

    private void newBookingAvailListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newBookingAvailListMouseClicked
        
        this.newBookingFormADateTextField.setText(this.newBookingFindSearchFromTextField.getText());
        this.newBookingFormNONTextField.setText(this.newBookingFindSearchNONTextField.getText());
            Apartment a = (Apartment) listModel.getElementAt(this.newBookingAvailList.getSelectedIndex());
        this.newBookingFormRoomTextField.setText(""+a.getA_num());
        this.enableComponents(this.newBookingFormPanel, true);
        this.enableComponents(this.newBookingFormGreyPanel, false);
    }//GEN-LAST:event_newBookingAvailListMouseClicked

    private void newBookingFormADateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBookingFormADateTextFieldActionPerformed
        //not supported
    }//GEN-LAST:event_newBookingFormADateTextFieldActionPerformed

    private void newBookingFormFirstTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBookingFormFirstTextFieldActionPerformed
        //not supported
    }//GEN-LAST:event_newBookingFormFirstTextFieldActionPerformed

    private void newBookingFormCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBookingFormCreateButtonActionPerformed
        Customer c = this.controller.addNewCustomer(this.newBookingFormFirstTextField.getText(), this.newBookingFormNameTextField.getText(), Integer.parseInt(this.newBookingFormAGETextField.getText()), this.newBookingFormEmailTextField.getText(), this.newBookingFormPhoneTextField.getText(), this.newBookingFormNatTextField.getText(), this.newBookingFormCityTextField.getText(), this.newBookingFormStreetTextField.getText(), Integer.parseInt(this.newBookingFormZipTextField.getText()));
        Apartment a = (Apartment) listModel.getElementAt(this.newBookingAvailList.getSelectedIndex());
        boolean success = this.controller.addNewBooking(c, a, Integer.parseInt(this.newBookingFormNONTextField.getText()), this.newBookingFormADateTextField.getText(), this.newBookingFormAgenTextField.getText(), a.getCost());
        if (success) {
            this.enableComponents(this, false);
            JOptionPane.showMessageDialog(this, "Booking created", "", WIDTH);
            this.enableComponents(this, true);
            this.enableComponents(this.newBookingFormPanel, false);
            this.enableComponents(this.newBookingAvailablePanel, false);
        }
    }//GEN-LAST:event_newBookingFormCreateButtonActionPerformed

    private void newBookingFormAgenTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBookingFormAgenTextFieldActionPerformed
        //not supported
    }//GEN-LAST:event_newBookingFormAgenTextFieldActionPerformed

    private void newBookingFormPreviousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBookingFormPreviousButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newBookingFormPreviousButtonActionPerformed

    private void newBookingAvailListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_newBookingAvailListValueChanged
    }//GEN-LAST:event_newBookingAvailListValueChanged

    private void newBookingFormButtonSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBookingFormButtonSaveButtonActionPerformed
        this.controller.saveTransaction();
    }//GEN-LAST:event_newBookingFormButtonSaveButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cl.show(mainPage, "FrontPage");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CasablancaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CasablancaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CasablancaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CasablancaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CasablancaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel editBookingPanel;
    private javax.swing.JButton frontPageEditBooking;
    private javax.swing.JButton frontPageExitButton;
    private javax.swing.JButton frontPageLogoutButton;
    private javax.swing.JPanel frontPageMenuPanel;
    private javax.swing.JPanel frontPageNavPanel;
    private javax.swing.JButton frontPageNewBooking;
    private javax.swing.JPanel frontPagePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JPanel mainPage;
    private javax.swing.JList newBookingAvailList;
    private javax.swing.JPanel newBookingAvailTitlePanel;
    private javax.swing.JLabel newBookingAvailTitleTitle;
    private javax.swing.JPanel newBookingAvailablePanel;
    private javax.swing.JButton newBookingFindButtonBackButton;
    private javax.swing.JButton newBookingFindButtonFindButton;
    private javax.swing.JPanel newBookingFindButtonPanel;
    private javax.swing.JPanel newBookingFindPanel;
    private javax.swing.JLabel newBookingFindSearchFromLabel;
    private javax.swing.JTextField newBookingFindSearchFromTextField;
    private javax.swing.JLabel newBookingFindSearchNONLabel;
    private javax.swing.JTextField newBookingFindSearchNONTextField;
    private javax.swing.JPanel newBookingFindSearchPanel;
    private javax.swing.JComboBox newBookingFindSearchTypeComboBox;
    private javax.swing.JLabel newBookingFindSearchTypeLabel;
    private javax.swing.JPanel newBookingFindTitlePanel;
    private javax.swing.JLabel newBookingFindTitleTitle;
    private javax.swing.JLabel newBookingFormADateLabel;
    private javax.swing.JTextField newBookingFormADateTextField;
    private javax.swing.JLabel newBookingFormAGELabel;
    private javax.swing.JTextField newBookingFormAGETextField;
    private javax.swing.JLabel newBookingFormAgenLabel;
    private javax.swing.JTextField newBookingFormAgenTextField;
    private javax.swing.JPanel newBookingFormButtonPanel;
    private javax.swing.JButton newBookingFormButtonSaveButton;
    private javax.swing.JLabel newBookingFormCityLabel;
    private javax.swing.JTextField newBookingFormCityTextField;
    private javax.swing.JButton newBookingFormCreateButton;
    private javax.swing.JLabel newBookingFormEmailLabel;
    private javax.swing.JTextField newBookingFormEmailTextField;
    private javax.swing.JLabel newBookingFormFirstLabel;
    private javax.swing.JTextField newBookingFormFirstTextField;
    private javax.swing.JPanel newBookingFormGreyPanel;
    private javax.swing.JLabel newBookingFormNOGLabel;
    private javax.swing.JTextField newBookingFormNOGTextField;
    private javax.swing.JLabel newBookingFormNONLabel;
    private javax.swing.JTextField newBookingFormNONTextField;
    private javax.swing.JLabel newBookingFormNameLabel;
    private javax.swing.JTextField newBookingFormNameTextField;
    private javax.swing.JLabel newBookingFormNatLabel;
    private javax.swing.JTextField newBookingFormNatTextField;
    private javax.swing.JPanel newBookingFormPanel;
    private javax.swing.JLabel newBookingFormPhoneLabel;
    private javax.swing.JTextField newBookingFormPhoneTextField;
    private javax.swing.JButton newBookingFormPreviousButton;
    private javax.swing.JLabel newBookingFormRoomLabel;
    private javax.swing.JTextField newBookingFormRoomTextField;
    private javax.swing.JLabel newBookingFormStreetLabel;
    private javax.swing.JTextField newBookingFormStreetTextField;
    private javax.swing.JPanel newBookingFormTitlePanel;
    private javax.swing.JLabel newBookingFormTitleTitle;
    private javax.swing.JTextField newBookingFormZipTextField;
    private javax.swing.JPanel newBookingPanel;
    private javax.swing.JPanel newBookingTitlePanel;
    private javax.swing.JLabel newBookingTitleTitle;
    // End of variables declaration//GEN-END:variables
}
